apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekEwTURndwpOakF3TUROYUZ3MDBNekEwTURnd05qQXdNRE5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDL05ySFpXTEk0K2lSek9hQVBDeUM4VUdBWG9UMmpRb2svYlZldzFjU1FaMTJ5SzZOYgpRNkxuUm9sSkZHQWdjU3d2T1MwYzNuNDlFSWhibnJwY2graWc3NHZ5UzN2c05RTFl5TGdEUFhFcDlMTlRoeWg3ClB3NzFOdDFack9jWGVOQTYwTkFOc01yUSt3bWJ1K0ZoUVN2UXg5S2lNeHBtMDl0czBMUnN6ZE5vQkFrMWJKQmYKZU5tdUU5T2FsS3pOeHBHUEdPYklQTTZKOXZZTklBbDhYSVM5YzhSNWg4UGs0a1NkU2hsK29CRzRsZ2kyeGhMRQpYRG1PbTFFL3g4NW4xMSt1ck9PVS94amVBaWtJenh3eUl6TDl4MmIwQXBSU1puNWJzbjltTE5NMTg3a2huVjhxCmhCdkZnQnJsR1I0ZXBLQ0NLaHZlWEtMV2hSQmxaQlEveVl0SkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlQrNUVNUFF3T2Q2WXpTMWZRdQp0Zi9IcU5CSzdUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFBc2xlK2ovSkw1Nmg1N0dBNE13SGVZcUtpRjBxCnl1SzAycGdnQ25uUm9EUHo3Z051bU5OMlFIT2M3TUFLQXJRWkNPNFNQVHU4Y1NrMnA4Z1E1bTZ4WjZDVjk1c0YKNTBkNThUcE8xMm0xUk9CNDUyOEJxZ0tkRGo0WmVnMVdBM2ZuMUtJTGFoWnowNVppY1NpQ01aMWVCc0ZvOXlCbwpuaVFqOVRSdmNteGQyd2RqMjVDcXp6bit3cXNrVzJ3djIvV29qY24yQ1VoTlNOak9Rakx1UXRyRm9HcXZ3Zi9aCjlsTDhHNCs0RGNmaWJPOGNVTFVkdWZTR3YrMVJscUJKZVZrOHRpR0VENFpGZEhSeGNEeWt5RjJsZFYwRW5ZRFQKeUFESm9DNkYxbUxncTBSU24vYyticlVMQ2hhWHhhUUlsRGlYRXdaMENxUFRpL3c5NERjR1cxdGFIUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e0791c21-2081-4352-8b53-7a853de3d601.k8s.ondigitalocean.com
  name: do-blr1-django-k8s
contexts:
- context:
    cluster: do-blr1-django-k8s
    user: do-blr1-django-k8s-admin
  name: do-blr1-django-k8s
current-context: do-blr1-django-k8s
kind: Config
preferences: {}
users:
- name: do-blr1-django-k8s-admin
  user:
    token: dop_v1_7d36aba1e6eaf57dbdaa51789de4c1f5809ef4260ddc53657fcbaaa3a079f098
